[package]
name = "tuic-quinn"
version = "0.1.0"
authors = ["EAimTY <ea.imty@gmail.com>"]
description = "A thin layer on top of quinn to provide functions for TUIC"
categories = ["network-programming"]
keywords = ["network", "proxy", "quic", "tuic"]
edition = "2021"
rust-version = "1.85.0"
readme = "README.md"
license = "GPL-3.0-or-later"
repository = "https://github.com/EAimTY/tuic"

[dependencies]
bytes = { version = "1.12.1", default-features = false, features = ["std"] }
futures-util = { version = "0.3.34", default-features = false, features = ["io", "std"] }
quinn = { version = "0.11.11", default-features = false, features = ["futures-io", "runtime-tokio", "rustls-ring"] }
thiserror = { version = "2.0.20", default-features = false }
tuic = { path = "../tuic", default-features = false, features = ["async_marshal", "marshal", "model"] }
uuid = { version = "1.26.0", default-features = false, features = ["std"] }

[dev-dependencies]
rcgen = { version = "0.14.10", default-features = false, features = ["ring"] }
rustls = { version = "0.23.43", default-features = false, features = ["ring", "std"] }
tokio = { version = "1.53.1", default-features = false, features = ["macros", "rt-multi-thread", "time"] }
